-- AlterTable
ALTER TABLE "Agent" ADD COLUMN "maxDailyTokens" INTEGER NOT NULL DEFAULT 500000;
ALTER TABLE "Agent" ADD COLUMN "dailyTokensUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Agent" ADD COLUMN "tokenCountDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
